name: tenis_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  bloc: ^8.1.2
  sqflite: ^2.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  
  test: ^1.16.0
  bloc_test: ^9.0.0
  mockito: ^5.4.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
